parameters:


services:
    # Applique des valeurs par défaut à tous les services (autowire et autoconfigure)
    _defaults:
        autowire: true       # Injection automatique des dépendances dans vos services
        autoconfigure: true  # Enregistrement automatique des services comme commandes, abonnés aux événements, etc.

    # Cela crée un service pour chaque classe dont l'identifiant est le nom complet de la classe
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/' # Exclure le dossier DependencyInjection
            - '../src/Entity/'              # Exclure le dossier Entity
            - '../src/Kernel.php'           # Exclure le fichier Kernel.php

    # Configuration du service Firebase avec le SDK Kreait Firebase
    Kreait\Firebase\Factory:
        class: Kreait\Firebase\Factory
        calls:
            - method: withServiceAccount
              arguments:
                  - '%env(FIREBASE_CREDENTIALS_PATH)%' # Spécifiez le chemin vers le fichier service-account.json

    # Service Firebase Auth pour gérer l'authentification et les rôles
    Kreait\Firebase\Auth:
        factory: ['@Kreait\Firebase\Factory', 'createAuth'] # Créer un service Firebase Auth avec la Factory

    # Service Firestore pour stocker les messages du formulaire de contact et les avis
    Kreait\Firebase\Firestore:
        factory: ['@Kreait\Firebase\Factory', 'createFirestore'] # Créer un service Firestore avec la Factory

    # Service Firebase Database pour une utilisation supplémentaire
    Kreait\Firebase\Database:
        factory: ['@Kreait\Firebase\Factory', 'createDatabase'] # Créer un service Database avec la Factory
