<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250122154314 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // Création de la table "cars"
        $this->addSql('CREATE TABLE cars (
            id SERIAL NOT NULL,
            model VARCHAR(255) NOT NULL,
            brand VARCHAR(255) NOT NULL,
            year INT NOT NULL,
            engine_type VARCHAR(10) NOT NULL,
            mileage INT NOT NULL,
            price DECIMAL(10, 2) NOT NULL,
            image VARCHAR(255) DEFAULT NULL,
            description TEXT DEFAULT NULL,
            PRIMARY KEY(id)
        )');

        // Création de la table "avis"
        $this->addSql('CREATE TABLE avis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, commentaire TEXT NOT NULL, note INT NOT NULL, approuve BOOLEAN NOT NULL, PRIMARY KEY(id))');
        
        // Suppression des tables non utilisées
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE horaire');
        $this->addSql('DROP TABLE information_garage');
        $this->addSql('DROP TABLE service');

        // Modification de la table "users"
        $this->addSql('ALTER TABLE users ADD first_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD last_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE users ADD is_active BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE users DROP login_attempts');
        $this->addSql('ALTER TABLE users DROP locked_until');
        $this->addSql('ALTER TABLE users DROP last_login_at');
    }

    public function down(Schema $schema): void
    {
        // Création des tables supprimées dans le "down"
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON messenger_messages (delivered_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE TABLE horaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jour VARCHAR(20) NOT NULL, heure_ouverture_matin VARCHAR(20) NOT NULL, heure_fermeture_matin VARCHAR(20) NOT NULL, heure_ouverture_aprem VARCHAR(20) NOT NULL, heure_fermeture_aprem VARCHAR(20) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE information_garage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, horaires VARCHAR(255) NOT NULL, adresse VARCHAR(255) NOT NULL, telephone VARCHAR(20) NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, categorie VARCHAR(50) NOT NULL, image_filename VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');

        // Suppression de la table "avis"
        $this->addSql('DROP TABLE avis');

        // Restauration des anciennes colonnes de la table "users"
        $this->addSql('ALTER TABLE users ADD login_attempts INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE users ADD locked_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE users DROP first_name');
        $this->addSql('ALTER TABLE users DROP last_name');
        $this->addSql('ALTER TABLE users DROP created_at');
        $this->addSql('ALTER TABLE users DROP is_active');
    }
}


