<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250123133043 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajout de la colonne locked_at à la table users et création de la table cars';
    }

    public function up(Schema $schema): void
    {
        // Ajout de la colonne locked_at à la table users
        $this->addSql('ALTER TABLE users ADD locked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');

        // Création de la table cars
        $this->addSql('CREATE TABLE cars (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            model VARCHAR(255) NOT NULL,
            brand VARCHAR(255) NOT NULL,
            year INT NOT NULL,
            engine_type VARCHAR(10) NOT NULL,
            mileage INT NOT NULL,
            price NUMERIC(10, 2) NOT NULL,
            image VARCHAR(255) DEFAULT NULL,
            description TEXT DEFAULT NULL,
            PRIMARY KEY(id)
        )');
    }

    public function down(Schema $schema): void
    {
        // Suppression de la table cars
        $this->addSql('DROP TABLE cars');

        // Suppression de la colonne locked_at de la table users
        $this->addSql('ALTER TABLE users DROP COLUMN locked_at');
    }
}