


# _____________________ sans la configuration de firebase ____________________________

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     expose:
#      - "9000"
#     environment:
#       DATABASE_URL: "postgresql://postgres:armanie@symfony_db:5432/garagevp?serverVersion=13&charset=utf8"
#       COMPOSER_ALLOW_SUPERUSER: "1"
#       PHP_OPCACHE_ENABLE: 1
#       PHP_OPCACHE_REVALIDATE_FREQ: 0
#       PHP_MEMORY_LIMIT: "512M"
#     container_name: symfony_app
#     working_dir: /var/www/html
#     volumes:
#       - ./:/var/www/html
#       - symfony_log:/var/www/html/var/log
#       - /docker/php/symfony.ini:/usr/local/etc/php/conf.d/symfony.ini
#     networks:
#       - symfony
#     depends_on:
#       - db
#     restart: unless-stopped

#   db:
#     image: postgres:13-alpine
#     container_name: symfony_db
#     environment:
#       POSTGRES_DB: garagevp
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: armanie
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - symfony
#     ports:
#       - 5432:5432
#     restart: unless-stopped


#   nginx:
#     build:
#       context: ./docker/nginx
#       dockerfile: Dockerfile
    
#     container_name: symfony_nginx
#     volumes:
#       - ./:/var/www/html
#       - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro  
#       - ./docker/ssl/localhost.crt:/etc/ssl/private/localhost.crt:ro   
#       - ./docker/ssl/localhost.key:/etc/ssl/private/localhost.key:ro   
#       - ./docker/ssl/rootCA.crt:/etc/ssl/private/rootCA.crt:ro  
#     ports:
#       - "80:80"
#       - "443:443"
#     depends_on:
#       - app
#     networks:
#       - symfony
#     restart: unless-stopped


# networks:
#   symfony:
#     driver: bridge

# volumes:
#   postgres_data:
#   symfony_log:






# ______________________version firebase ____________________

  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      expose:
      - "9000"
      environment:
        DATABASE_URL: "postgresql://postgres:armanie@symfony_db:5432/garagevp?serverVersion=13&charset=utf8"
        COMPOSER_ALLOW_SUPERUSER: "1"
        PHP_OPCACHE_ENABLE: 1
        PHP_OPCACHE_REVALIDATE_FREQ: 0
        PHP_MEMORY_LIMIT: "512M"
      container_name: symfony_app
      working_dir: /var/www/html
      volumes:
        - ./:/var/www/html
        - symfony_log:/var/www/html/var/log
        - /docker/php/symfony.ini:/usr/local/etc/php/conf.d/symfony.ini
      networks:
        - symfony
      depends_on:
        - db
      restart: unless-stopped

    db:
      image: postgres:13-alpine
      container_name: symfony_db
      environment:
        POSTGRES_DB: garagevp
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: armanie
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - symfony
      ports:
        - 5432:5432
      restart: unless-stopped


    nginx:
      build:
        context: ./docker/nginx
        dockerfile: Dockerfile
      
      container_name: symfony_nginx
      volumes:
        - ./:/var/www/html
        - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro  
        - ./docker/ssl/localhost.crt:/etc/ssl/private/localhost.crt:ro   
        - ./docker/ssl/localhost.key:/etc/ssl/private/localhost.key:ro   
        - ./docker/ssl/rootCA.crt:/etc/ssl/private/rootCA.crt:ro  
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - app
      networks:
        - symfony
      restart: unless-stopped



  networks:
    symfony:
      driver: bridge

  volumes:
    postgres_data:
    symfony_log:








