# services:
#   app:
#     image: php:8.2-fpm
#     container_name: symfony_app
#     working_dir: /var/www/html
#     volumes:
#       - ./:/var/www/html
#     networks:
#       - symfony

#   database:
#     image: postgres:13
#     container_name: symfony_db
#     environment:
#       POSTGRES_DB: garagevp
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: armanie
#     networks:
#       - symfony
#     ports:
#       - 5432:5432

#   nginx:
#     image: nginx:alpine
#     container_name: symfony_nginx
#     volumes:
#       - ./:/var/www/html
#       - ./docker/nginx/conf.d:/etc/nginx/conf.d
#     ports:
#       - "8080:80"
#     depends_on:
#       - app
#     networks:
#       - symfony

# networks:
#   symfony:
#     driver: bridge




services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - symfony

  db:
    image: postgres:13
    container_name: symfony_db
    environment:
      POSTGRES_DB: garagevp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: armanie
    networks:
      - symfony
    ports:
      - 5432:5432

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - symfony

networks:
  symfony:
    driver: bridge




