# services:
#   - type: web
#     name: symfony-app
#     env: docker
#     plan: free
#     repo: https://github.com/yayabalti/Garagevp2
#     branch: main
#     dockerfilePath: ./Dockerfile
#     buildCommand: ""
#     startCommand: ""
#     envVars:
#       - key: APP_ENV
#         value: prod
#       - key: APP_SECRET
#         value: TaCléSecrèteSymfony123
#       - key: DATABASE_URL
#         fromDatabase:
#           name: symfony-db
#           property: connectionString


services:
  - type: web
    name: garagevp2
    env: docker
    plan: free
    repo: https://github.com/yayabalti/Garagevp2
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "/start.sh"
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        value: e73ec45580c5b9c19208fa3d19f9215a
      - key: DATABASE_URL
        fromDatabase:
          name: symfony-db
          property: connectionString
      - key: TRUSTED_PROXIES
        value: 0.0.0.0/0
      - key: TRUSTED_HOSTS
        value: garagevp2.onrender.com

