easy_admin:
    entities:
        Car:
            class: App\Entity\Car
            controller: App\Controller\Admin\CarCrudController
            label: 'Voitures'
            list:
                title: 'Liste des Voitures'
                filters:
                    - { property: 'brand', label: 'Marque', type: 'choice', choices: 
                        {'Peugeot': 'Peugeot', 'Renault': 'Renault', 'Audi': 'Audi', 'BMW': 'BMW', 'Mercedes': 'Mercedes'} }
                    - { property: 'engineType', label: 'Type de carburant', type: 'choice', choices: 
                        {'Diesel': 'diesel', 'Essence': 'essence'} }
                    - { property: 'year', label: 'Année de mise en circulation' }
                    - { property: 'mileage', label: 'Kilométrage' }
                    - { property: 'price', label: 'Prix' }
            form:
                fields:
                    - { property: 'model', label: 'Modèle' }
                    - { property: 'brand', label: 'Marque' }
                    - { property: 'year', label: 'Année' }
                    - { property: 'engineType', label: 'Type de carburant' }
                    - { property: 'mileage', label: 'Kilométrage' }
                    - { property: 'price', label: 'Prix' }
                    - { property: 'image', label: 'Image' }
                    - { property: 'description', label: 'Description' }
            security:
                roles:
                    - ROLE_EMPLOYE
    



   
              

