# framework:
#     notifier:
#         chatter_transports:
#         texter_transports:
#         channel_policy:
#             # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
#             urgent: ['email']
#             high: ['email']
#             medium: ['email']
#             low: ['email']
#         admin_recipients:
#             - { email: admin@example.com }




framework:
   # Clé secrète
   secret: '%env(APP_SECRET)%'
   
   # Protection CSRF
   csrf_protection: true
   
   # Sessions
   session:
       enabled: true
       storage_factory_id: session.storage.factory.native
       cookie_secure: auto
       cookie_samesite: 'lax'
       cookie_httponly: true
   
   # Désactivation features non utilisées
   esi: false
   fragments: false
   
   # Validation
   validation:
       enable_attributes: true

   # Configuration notifier
   notifier:
       chatter_transports:
       texter_transports:
       channel_policy:
           urgent: ['email']
           high: ['email']
           medium: ['email']
           low: ['email']
       admin_recipients:
           - { email: admin@example.com }

when@test:
   framework:
       test: true
       session:
           storage_factory_id: session.storage.factory.mock_file
