# security:
#     password_hashers:
#         App\Entity\User:
#             algorithm: auto
    
#     providers:
#         app_user_provider:
#             entity:
#                 class: App\Entity\User
#                 property: email
    
#     firewalls:
#         dev:
#             pattern: ^/(_(profiler|wdt)|css|images|js)/
#             security: false
#         main:
#             lazy: true
#             provider: app_user_provider
#             custom_authenticator: App\Security\LoginFormAuthenticator
#             logout:
#                 path: app_logout
#                 target: app_home
#             remember_me:
#                 secret: '%kernel.secret%'
#                 lifetime: 604800
#                 secure: true
    
#     access_control:
#         - { path: ^/login, roles: PUBLIC_ACCESS }
#         - { path: ^/admin, roles: ROLE_ADMIN }
#         - { path: ^/, roles: PUBLIC_ACCESS }


security:
    
    password_hashers:
        App\Entity\User:
            algorithm: 'auto'  
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true  # Protection CSRF
            entry_point: form_login
            logout:
                path: app_logout
                target: app_home
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                secure: true
                always_remember_me: true
            login_throttling:
                max_attempts: 3
                interval: '15 minutes'
    
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: PUBLIC_ACCESS }

