# security:
#     password_hashers:
#         App\Entity\User:
#             algorithm: auto
    
#     providers:
#         app_user_provider:
#             entity:
#                 class: App\Entity\User
#                 property: email
    
#     firewalls:
#         dev:
#             pattern: ^/(_(profiler|wdt)|css|images|js)/
#             security: false
#         main:
#             lazy: true
#             provider: app_user_provider
#             custom_authenticator: App\Security\LoginFormAuthenticator
#             logout:
#                 path: app_logout
#                 target: app_home
#             remember_me:
#                 secret: '%kernel.secret%'
#                 lifetime: 604800
#                 secure: true
    
#     access_control:
#         - { path: ^/login, roles: PUBLIC_ACCESS }
#         - { path: ^/admin, roles: ROLE_ADMIN }
#         - { path: ^/, roles: PUBLIC_ACCESS }


security:
    
    password_hashers:
        App\Entity\User:
            algorithm: 'auto'  
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true  # Protection CSRF
            entry_point: form_login
            logout:
                path: app_logout
                target: app_home
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                secure: true
                always_remember_me: true
            login_throttling:
                max_attempts: 3
                interval: '15 minutes'

        # Pour l'admin (EasyAdmin pour l'admin)
        easyadmin_admin:
            pattern: ^/admin  # Cette règle concerne toutes les pages qui commencent par '/admin'
            security: true     # Assure que cette route est protégée
            # Pas besoin de "roles" ici, ils sont gérés dans access_control

        # Pour l'employé (tableau de bord personnalisé pour l'employé)
        easyadmin_employe:
            pattern: ^/easyemploye/dashboard  # Cette règle concerne l'interface spécifique à l'employé
            security: true      # Protection de la route
            # Pas besoin de "roles" ici, ils sont gérés dans access_control

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }  # La page de connexion est accessible à tous
        - { path: ^/easyemploye/dashboard, roles: ROLE_EMPLOYE }  # Seul un utilisateur avec le rôle ROLE_EMPLOYE peut accéder à /easyemploye/dashboard
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: PUBLIC_ACCESS } # Le reste des pages est accessible à tous
        

    
    

